######################################################################
#
# File name : cordicTest_test_compile.do
# Created on: Tue Sep 22 23:56:45 +0300 2020
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
D:\\Modeltech_pe_edu_10.4a\\win32pe_edu\\vlib modelsim_lib/work
D:\\Modeltech_pe_edu_10.4a\\win32pe_edu\\vlib modelsim_lib/msim

D:\\Modeltech_pe_edu_10.4a\\win32pe_edu\\vlib modelsim_lib/msim/xbip_utils_v3_0_10
D:\\Modeltech_pe_edu_10.4a\\win32pe_edu\\vlib modelsim_lib/msim/c_reg_fd_v12_0_6
D:\\Modeltech_pe_edu_10.4a\\win32pe_edu\\vlib modelsim_lib/msim/xbip_dsp48_wrapper_v3_0_4
D:\\Modeltech_pe_edu_10.4a\\win32pe_edu\\vlib modelsim_lib/msim/xbip_pipe_v3_0_6
D:\\Modeltech_pe_edu_10.4a\\win32pe_edu\\vlib modelsim_lib/msim/xbip_dsp48_addsub_v3_0_6
D:\\Modeltech_pe_edu_10.4a\\win32pe_edu\\vlib modelsim_lib/msim/xbip_addsub_v3_0_6
D:\\Modeltech_pe_edu_10.4a\\win32pe_edu\\vlib modelsim_lib/msim/c_addsub_v12_0_14
D:\\Modeltech_pe_edu_10.4a\\win32pe_edu\\vlib modelsim_lib/msim/xbip_bram18k_v3_0_6
D:\\Modeltech_pe_edu_10.4a\\win32pe_edu\\vlib modelsim_lib/msim/mult_gen_v12_0_16
D:\\Modeltech_pe_edu_10.4a\\win32pe_edu\\vlib modelsim_lib/msim/axi_utils_v2_0_6
D:\\Modeltech_pe_edu_10.4a\\win32pe_edu\\vlib modelsim_lib/msim/cordic_v6_0_16
D:\\Modeltech_pe_edu_10.4a\\win32pe_edu\\vlib modelsim_lib/msim/xil_defaultlib

D:\\Modeltech_pe_edu_10.4a\\win32pe_edu\\vmap xbip_utils_v3_0_10 modelsim_lib/msim/xbip_utils_v3_0_10
D:\\Modeltech_pe_edu_10.4a\\win32pe_edu\\vmap c_reg_fd_v12_0_6 modelsim_lib/msim/c_reg_fd_v12_0_6
D:\\Modeltech_pe_edu_10.4a\\win32pe_edu\\vmap xbip_dsp48_wrapper_v3_0_4 modelsim_lib/msim/xbip_dsp48_wrapper_v3_0_4
D:\\Modeltech_pe_edu_10.4a\\win32pe_edu\\vmap xbip_pipe_v3_0_6 modelsim_lib/msim/xbip_pipe_v3_0_6
D:\\Modeltech_pe_edu_10.4a\\win32pe_edu\\vmap xbip_dsp48_addsub_v3_0_6 modelsim_lib/msim/xbip_dsp48_addsub_v3_0_6
D:\\Modeltech_pe_edu_10.4a\\win32pe_edu\\vmap xbip_addsub_v3_0_6 modelsim_lib/msim/xbip_addsub_v3_0_6
D:\\Modeltech_pe_edu_10.4a\\win32pe_edu\\vmap c_addsub_v12_0_14 modelsim_lib/msim/c_addsub_v12_0_14
D:\\Modeltech_pe_edu_10.4a\\win32pe_edu\\vmap xbip_bram18k_v3_0_6 modelsim_lib/msim/xbip_bram18k_v3_0_6
D:\\Modeltech_pe_edu_10.4a\\win32pe_edu\\vmap mult_gen_v12_0_16 modelsim_lib/msim/mult_gen_v12_0_16
D:\\Modeltech_pe_edu_10.4a\\win32pe_edu\\vmap axi_utils_v2_0_6 modelsim_lib/msim/axi_utils_v2_0_6
D:\\Modeltech_pe_edu_10.4a\\win32pe_edu\\vmap cordic_v6_0_16 modelsim_lib/msim/cordic_v6_0_16
D:\\Modeltech_pe_edu_10.4a\\win32pe_edu\\vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib

D:\\Modeltech_pe_edu_10.4a\\win32pe_edu\\vcom -64 -93 -work xbip_utils_v3_0_10  \
"../../../../AlgorithmTest.ip_user_files/ipstatic/hdl/xbip_utils_v3_0_vh_rfs.vhd" \

D:\\Modeltech_pe_edu_10.4a\\win32pe_edu\\vcom -64 -93 -work c_reg_fd_v12_0_6  \
"../../../../AlgorithmTest.ip_user_files/ipstatic/hdl/c_reg_fd_v12_0_vh_rfs.vhd" \

D:\\Modeltech_pe_edu_10.4a\\win32pe_edu\\vcom -64 -93 -work xbip_dsp48_wrapper_v3_0_4  \
"../../../../AlgorithmTest.ip_user_files/ipstatic/hdl/xbip_dsp48_wrapper_v3_0_vh_rfs.vhd" \

D:\\Modeltech_pe_edu_10.4a\\win32pe_edu\\vcom -64 -93 -work xbip_pipe_v3_0_6  \
"../../../../AlgorithmTest.ip_user_files/ipstatic/hdl/xbip_pipe_v3_0_vh_rfs.vhd" \

D:\\Modeltech_pe_edu_10.4a\\win32pe_edu\\vcom -64 -93 -work xbip_dsp48_addsub_v3_0_6  \
"../../../../AlgorithmTest.ip_user_files/ipstatic/hdl/xbip_dsp48_addsub_v3_0_vh_rfs.vhd" \

D:\\Modeltech_pe_edu_10.4a\\win32pe_edu\\vcom -64 -93 -work xbip_addsub_v3_0_6  \
"../../../../AlgorithmTest.ip_user_files/ipstatic/hdl/xbip_addsub_v3_0_vh_rfs.vhd" \

D:\\Modeltech_pe_edu_10.4a\\win32pe_edu\\vcom -64 -93 -work c_addsub_v12_0_14  \
"../../../../AlgorithmTest.ip_user_files/ipstatic/hdl/c_addsub_v12_0_vh_rfs.vhd" \

D:\\Modeltech_pe_edu_10.4a\\win32pe_edu\\vcom -64 -93 -work xbip_bram18k_v3_0_6  \
"../../../../AlgorithmTest.ip_user_files/ipstatic/hdl/xbip_bram18k_v3_0_vh_rfs.vhd" \

D:\\Modeltech_pe_edu_10.4a\\win32pe_edu\\vcom -64 -93 -work mult_gen_v12_0_16  \
"../../../../AlgorithmTest.ip_user_files/ipstatic/hdl/mult_gen_v12_0_vh_rfs.vhd" \

D:\\Modeltech_pe_edu_10.4a\\win32pe_edu\\vcom -64 -93 -work axi_utils_v2_0_6  \
"../../../../AlgorithmTest.ip_user_files/ipstatic/hdl/axi_utils_v2_0_vh_rfs.vhd" \

D:\\Modeltech_pe_edu_10.4a\\win32pe_edu\\vcom -64 -93 -work cordic_v6_0_16  \
"../../../../AlgorithmTest.ip_user_files/ipstatic/hdl/cordic_v6_0_vh_rfs.vhd" \

D:\\Modeltech_pe_edu_10.4a\\win32pe_edu\\vcom -64 -93 -work xil_defaultlib  \
"../../../../AlgorithmTest.srcs/sources_1/ip/cordic_case_1/sim/cordic_case_1.vhd" \

D:\\Modeltech_pe_edu_10.4a\\win32pe_edu\\vlog -64 -incr -work xil_defaultlib  \
"../../../../AlgorithmTest.srcs/sources_1/new/cordicTest.v" \
"../../../../AlgorithmTest.srcs/sim_1/new/cordicTest_test.v" \

# compile glbl module
D:\\Modeltech_pe_edu_10.4a\\win32pe_edu\\vlog -work xil_defaultlib "glbl.v"

quit -force

