function Hd = filterDesign(N,Fpass,Fstop,Wpass,Wstop)
%FILTERDESIGN Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.4 and DSP System Toolbox 9.6.
% Generated on: 26-Dec-2020 17:43:10

% Equiripple Lowpass filter designed using the FIRPM function.

% All frequency values are normalized to 1.


%N     = 255;   % Order
%Fpass = 0.01;  % Passband Frequency
%Fstop = 0.02;  % Stopband Frequency
%Wpass = 1;     % Passband Weight
%Wstop = 80;    % Stopband Weight
dens  = 20;    % Density Factor

% Calculate the coefficients using the FIRPM function.
b  = firpm(N, [0 Fpass Fstop 1], [1 1 0 0], [Wpass Wstop], {dens});
Hd = dfilt.dffir(b);
%Hd = b;
% [EOF]
