#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2020.2 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Thu Feb 03 18:06:35 +03 2022
# SW Build 3064766 on Wed Nov 18 09:12:47 MST 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# elaborate design
echo "xelab -wto 1a50636ede72487094fbcb7cc6df798d --incr --debug typical --relax --mt 8 -L xil_defaultlib -L xbip_utils_v3_0_10 -L xbip_pipe_v3_0_6 -L xbip_bram18k_v3_0_6 -L mult_gen_v12_0_16 -L uvm -L unisims_ver -L unimacro_ver -L secureip -L xpm --snapshot timeSynchronizer_tb_behav xil_defaultlib.timeSynchronizer_tb xil_defaultlib.glbl -log elaborate.log"
xelab -wto 1a50636ede72487094fbcb7cc6df798d --incr --debug typical --relax --mt 8 -L xil_defaultlib -L xbip_utils_v3_0_10 -L xbip_pipe_v3_0_6 -L xbip_bram18k_v3_0_6 -L mult_gen_v12_0_16 -L uvm -L unisims_ver -L unimacro_ver -L secureip -L xpm --snapshot timeSynchronizer_tb_behav xil_defaultlib.timeSynchronizer_tb xil_defaultlib.glbl -log elaborate.log

