#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2020.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Thu Feb 03 18:04:52 +03 2022
# SW Build 3064766 on Wed Nov 18 09:12:47 MST 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim timeSynchronizer_tb_behav -key {Behavioral:sim_1:Functional:timeSynchronizer_tb} -tclbatch timeSynchronizer_tb.tcl -view /home/soganli/VivadoProjects/algorithmDev/algorithmDev.srcs/sim_1/imports/AlgorithmTest/fftDecimatorTrigger_test_behav.wcfg -log simulate.log"
xsim timeSynchronizer_tb_behav -key {Behavioral:sim_1:Functional:timeSynchronizer_tb} -tclbatch timeSynchronizer_tb.tcl -view /home/soganli/VivadoProjects/algorithmDev/algorithmDev.srcs/sim_1/imports/AlgorithmTest/fftDecimatorTrigger_test_behav.wcfg -log simulate.log

